version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./social_network/social_network/.env
  web:
    build: .
    restart: always
    volumes:
      - static_value:/app/social_network/static/
      - media_value:/app/social_network/media/
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./social_network/social_network/.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value: